### ISSUE TITLE
Unresolved attribute reference 'current_page' for class 'Menu'

### ISSUE THREAD

**Issue by rosesaredumb** [Rapptz/discord-ext-menus#18]
how do i fix this?
Unresolved attribute reference 'current_page' for class 'Menu'

```    
async def format_page(self, menu, entries):
        offset = (menu.current_page * self.per_page) + 1
```

**Comment by Rapptz** [comment]
This is a linter error. Type hint the argument or just ignore it, e.g. `async def format_page(self, menu: menu.MenuPages, entries):`
