### ISSUE TITLE
Menu.start() cannot send to DMs

### ISSUE THREAD

**Issue by tuzonghua** [Rapptz/discord-ext-menus#40]
`Menu.start()` accepts a `channel` argument of type `discord.abc.Messageable`, which _should_ mean menus can be sent to DMs. However, it looks like it calls `permissions_for` [here](https://github.com/Rapptz/discord-ext-menus/blob/master/discord/ext/menus/__init__.py#L701), which doesn't exist on the `discord.Member` class, even though that class implements the `Messageable` ABC. 

For example, this returns an error `AttributeError: 'Member' object has no attribute 'permissions_for'`:
```
@bot.command()
async def menu_example(ctx):
    m = MyMenu()
    await m.start(ctx, channel=ctx.author)
```

Let me know if I'm misunderstanding how this should work.

**Comment by diceroll123** [comment]
You're going to have to use a modified context if you're going to... change the context of the command mid-way.

**Comment by snvgglebear** [comment]
You can override the send_initial_message function and use ctx.author.send.

**Comment by diceroll123** [comment]
I missed your original point, OP.

What's wrong here is that you're calling a Member object a Messageable object.

Simply do 

```python
dm = await ctx.author.create_dm()
await m.start(ctx, channel=dm)
```

And it shoooould work

**Comment by tuzonghua** [comment]
@diceroll123 Yes, that worked perfectly. I just missed how to get a `DMChannel` to call `start()` with.
